# Generated by Django 5.2.6 on 2025-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='off_days',
        ),
        migrations.AddField(
            model_name='employee',
            name='holidays',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
