# Generated by Django 5.2.6 on 2025-09-08 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_remove_employee_off_days_employee_holidays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='holidays',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='max_days',
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_range', models.CharField(blank=True, max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shifts.employee')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
