# Generated by Django 5.2.6 on 2025-09-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_employee_holidays_employee_max_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='holidays',
        ),
        migrations.AlterField(
            model_name='employee',
            name='max_days',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='employee',
            name='holidays',
            field=models.ManyToManyField(blank=True, to='shifts.holiday'),
        ),
    ]
