# Generated by Django 5.2.4 on 2025-09-09 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_remove_employee_holidays_holiday_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='スタッフ', max_length=50),
        ),
        migrations.CreateModel(
            name='RequestedOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_off_dates', to='shifts.employee')),
            ],
        ),
    ]
