# Generated by Django 5.2.6 on 2025-09-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_days', models.IntegerField(default=5)),
                ('off_days', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
