# Generated by Django 5.2.6 on 2025-09-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_remove_employee_holidays_remove_employee_max_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='holidays',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='max_days',
            field=models.IntegerField(default=0),
        ),
    ]
