# Generated by Django 5.2.6 on 2025-09-08 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_holiday_remove_employee_holidays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='holidays',
        ),
        migrations.AddField(
            model_name='holiday',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='shifts.employee'),
        ),
    ]
