# Generated by Django 5.2.6 on 2025-09-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_employee_role_requestedoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')], unique=True)),
                ('min_staff', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', '正社員'), ('staff', '準社'), ('part', 'アルバイト')], default='staff', max_length=20),
        ),
    ]
